/// First non-comment line must define using the proto3 syntax.
syntax = "proto3";

/// Define the package name we are using
package tk.sim_msgs;

/// Import common message definitions
import "gz/msgs/header.proto";

// message describing wheels state
message ClutchState
{
  enum ControlType
  {
    AUTOMATIC  = 0;
    USER_INPUT = 1;
    MANUAL     = 2;
  }

  gz.msgs.Header header       = 1;  // header data
  ControlType    control_type = 2;
  float          inertia      = 3;
  float          engagement   = 4;
}
